### ISSUE TITLE
standard algorithms

### ISSUE THREAD

**Issue by kloetzl** [EvolBioInf/sid#1]
https://github.com/EvolBioInf/sid/blob/master/likelihoods.cpp#L157-L165 kann durch ein `std::max_element` ersetzt werden.

https://github.com/EvolBioInf/sid/blob/master/likelihoods.cpp#L141-L155 dagegen ist ein `std::accumulate`.

Gruß aus Griechenland. ☺
Fabian

**Comment by lweckeck** [comment]
Danke für die Tipps, ich ändere das mal. Die erste Funktion ist mitterweile überflüssig, die kommt dann ganz weg. ;-)
